# Generated by Django 3.1.2 on 2020-10-02 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('private', models.BooleanField(default=False)),
                ('photo', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_one_id', models.CharField(max_length=80)),
                ('user_two_id', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_id', to=settings.AUTH_USER_MODEL)),
                ('lender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_id', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.lookup')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.lookup'),
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
