# Generated by Django 3.1.2 on 2020-10-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshare',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookshare',
            old_name='borrower_id',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='bookshare',
            old_name='lender_id',
            new_name='lender',
        ),
    ]
